import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { Aimex } from '../projects/Aimex';
import { Economico } from '../projects/Economico';
import { SocredConsignado } from '../projects/SocredConsignado';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [search, setSearch] = useState('');

  //CRIE UM NOVO OBJETO PARA QUE SUA ROTA SEJA MOSTRADA NA BARRA DE PESQUISA.
  const Links = [
    {
      id: 1,
      name: 'Artmil',
      href: '/artmil',
    },
    {
      id: 2,
      name: 'Econômico',
      href: '/economico',
    },
    {
      id: 3,
      name: 'Aimex',
      href: '/aimex',
    },
    {
      id: 4,
      name: 'Círio App',
      href: '/cirio',
    },
    {
      id: 5,
      name: 'Viena',
      href: '/viena',
    },
    {
      id: 6,
      name: 'Eduardo Mello',
      href: '/eduardo-mello',
    },
    {
      id: 7,
      name: 'Atlântica Matapi',
      href: '/atlantica-matapi',
    },
    {
      id: 8,
      name: 'ISSAA',
      href: '/issaa',
    },
    {
      id: 9,
      name: 'Recicle',
      href: '/recicle',
    },
    {
      id: 10,
      name: 'Certify',
      href: '/certify',
    },
    {
      id: 11,
      name: 'Ekoar',
      href: '/ekoar',
    },
    {
      id: 12,
      name: 'Manuella Melo',
      href: '/manuella-melo',
    },
    {
      id: 13,
      name: 'Assembleia Paraense',
      href: '/assembleia-paraense',
    },
    {
      id: 14,
      name: 'CDR App',
      href: '/cdr-app',
    },
    {
      id: 15,
      name: 'Estrutura Engenharia',
      href: '/estrutura-engenharia',
    },
    {
      id: 15,
      name: 'Santa Dica',
      href: '/santa-dica',
    },
    {
      id: 16,
      name: 'Video 4 School',
      href: '/video4school',
    },
    {
      id: 17,
      name: 'Aplicativo Pro.Ver',
      href: '/app-pro-ver',
    },
    {
      id: 18,
      name: 'Simineral',
      href: '/simineral',
    },
    {
      id: 19,
      name: 'Aqualand',
      href: '/aqualand',
    },
    {
      id: 20,
      name: 'Quadra',
      href: '/quadra',
    },
    {
      id: 21,
      name: 'Paysandu',
      href: '/paysandu',
    },
    {
      id: 22,
      name: 'Amat',
      href: '/amat-carajas',
    },
    {
      id: 23,
      name: 'oab',
      href: '/oab',
    },
    {
      id: 24,
      name: 'Cablim',
      href: '/cablim',
    },
    {
      id: 25,
      name: 'APP APEPA',
      href: '/app-apepa',
    },
    {
      id: 26,
      name: 'APP Discontapp',
      href: '/app-discontapp',
    },
  ];

  const filter = links => {
    return links
      .filter(link => {
        return search == ''
          ? link
          : link.name.toLocaleLowerCase().includes(search.toLocaleLowerCase());
      })
      .map((item, key) => {
        return (
          <>
            <Link key={key} href={item.href}>
              {item.name}
            </Link>
            <br />
          </>
        );
      });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <label htmlFor="search" className={styles.label}>
          <small>Search:</small>
          <input
            type="text"
            placeholder="Search here..."
            id="search"
            onChange={e => setSearch(e.target.value)}
            className={styles.input}
          />
        </label>
        {filter(Links)}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
